```puml

@startuml

class Musician {
    + produceSound(UDP, Multicast)
}

class Auditor {
    + TCP_Server
    + getSound()
    + createJSONObject()
    + sendOrchstra()
}

class TCP_Client {
    + getOrchestra()
}

Musician --> Auditor : "send sound"

Auditor --> TCP_Client : "JSON object"

TCP_Client --> Auditor : "request JSON"

@enduml

```